CREATE TABLE SHOP (
	SHOPID INT,
	SHOPNAME VARCHAR(100),
	CITYNAME VARCHAR(50),
	REGIONNAME VARCHAR(50),
	COUNTRYNAME VARCHAR(50),
	PRIMARY KEY (SHOPID)
);

CREATE TABLE ARTICLE (
	ArticleID INT,
	ArticleName VARCHAR(100),
	ProductGroupName VARCHAR(50),
	ProductFamilyName VARCHAR(50),
	ProductCategoryName VARCHAR(50),
	PRIMARY KEY (ArticleID)
);

CREATE TABLE SALE_DATE (
	DATEID INT,
	DAY INT,
	MONTH INT,
	QUARTER INT,
	YEAR INT,
	PRIMARY KEY (DATEID)
);

CREATE TABLE SALE (
	DATEID INT, -- renamed because 'date' is reserved
	SHOPID INT,
	ARTICLEID INT,
	SALES INT,
	REVENUE REAL,
	PRIMARY KEY (DATEID, SHOPID, ARTICLEID), -- try it like this ;)
	FOREIGN KEY (DATEID) REFERENCES SALE_DATE (DATEID),
	FOREIGN KEY (SHOPID) REFERENCES SHOP (SHOPID),
	FOREIGN KEY (ARTICLEID) REFERENCES ARTICLE (ARTICLEID)
);

SELECT SUM(sa.SALES), SUM(sa.REVENUE), d.DATEID
FROM SALE sa
  INNER JOIN SHOP sh ON sa.SHOPID = sh.SHOPID
  INNER JOIN ARTICLE a ON sa.ARTICLEID = a.ARTICLEID
  INNER JOIN SALE_DATE d ON sa.DATEID = d.DATEID
WHERE 1 = 1 -- TODO
GROUP BY d.DATEID;

