SELECT SUM(S.SALES) AS SALES, A.PRODUCTGROUPNAME, SH.REGIONNAME, D.YEAR
FROM SHOP SH, ARTICLE A, SALE_DATE D, SALE S
WHERE S.SHOPID = SH.SHOPID AND
	  S.ARTICLEID = A.ARTICLEID AND
	  S.DATEID = D.DATEID
GROUP BY GROUPING SETS((D.YEAR, SH.REGIONNAME, A.PRODUCTGROUPNAME), (A.PRODUCTGROUPNAME)); --GROUPING SETS ((SH.CITYNAME, D.QUARTER), (SH.CITYNAME), (A.ARTICLENAME, D.QUARTER));


SELECT SUM(S.SALES) AS SALES,  SH.REGIONNAME, D.YEAR, D.QUARTER, D.MONTH
FROM SHOP SH, ARTICLE A, SALE_DATE D, SALE S
WHERE S.SHOPID = SH.SHOPID AND
	  S.ARTICLEID = A.ARTICLEID AND
	  S.DATEID = D.DATEID
GROUP BY (D.MONTH, D.QUARTER, D.YEAR, SH.REGIONNAME);


SELECT SUM(S.SALES) AS SALES, A.PRODUCTGROUPNAME, SH.COUNTRYNAME, D.YEAR
FROM SHOP SH, ARTICLE A, SALE_DATE D, SALE S
WHERE S.SHOPID = SH.SHOPID AND
	  S.ARTICLEID = A.ARTICLEID AND
	  S.DATEID = D.DATEID
GROUP BY CUBE(D.YEAR, SH.COUNTRYNAME, A.PRODUCTGROUPNAME);

SELECT COUNT(*) FROM SALE; --77308

SELECT COUNT(*) FROM SALE_DATE; --151

SELECT COUNT(*) FROM ARTICLE; --32

SELECT COUNT(*) FROM SHOP; --16

SELECT * FROM SALE_DATE;


SELECT SUM(S.SALES) AS SALES, A.ARTICLENAME, SH.REGIONNAME, D.QUARTER, D.YEAR
FROM SHOP SH, ARTICLE A, SALE_DATE D, SALE S
WHERE S.SHOPID = SH.SHOPID AND
	  S.ARTICLEID = A.ARTICLEID AND
	  S.DATEID = D.DATEID
GROUP BY ROLLUP(A.ARTICLENAME, SH.REGIONNAME, D.YEAR, D.QUARTER);

-- Tests

SELECT SUM(S.SALES) AS SALES, A.PRODUCTCATEGORYNAME, SH.COUNTRYNAME, D.YEAR
FROM SHOP SH, ARTICLE A, SALE_DATE D, SALE S
WHERE S.SHOPID = SH.SHOPID AND
	  S.ARTICLEID = A.ARTICLEID AND
	  S.DATEID = D.DATEID
GROUP BY ROLLUP(A.PRODUCTCATEGORYNAME, SH.COUNTRYNAME, D.YEAR);

SELECT SUM(S.SALES) AS SALES, A.ARTICLENAME, SH.SHOPNAME, D.DAY, D.MONTH, D.QUARTER, D.YEAR
FROM SHOP SH, ARTICLE A, SALE_DATE D, SALE S
WHERE S.SHOPID = SH.SHOPID AND
	  S.ARTICLEID = A.ARTICLEID AND
	  S.DATEID = D.DATEID
GROUP BY ROLLUP(A.ARTICLENAME, SH.SHOPNAME, D.DAY, D.MONTH, D.QUARTER, D.YEAR);

SELECT SUM(S.SALES) AS SALES, D.DAY, D.MONTH
FROM SHOP SH, ARTICLE A, SALE_DATE D, SALE S
WHERE S.SHOPID = SH.SHOPID AND
	  S.ARTICLEID = A.ARTICLEID AND
	  S.DATEID = D.DATEID
GROUP BY  D.DAY, D.MONTH;
